export enum ErrorCode {
  // Client errors (4xx)
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // Business logic errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  INSUFFICIENT_RESOURCES = 'INSUFFICIENT_RESOURCES',
  OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',

  // Integration errors
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT',
  INTEGRATION_ERROR = 'INTEGRATION_ERROR',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',

  // Data errors
  DATA_NOT_FOUND = 'DATA_NOT_FOUND',
  DATA_INTEGRITY_ERROR = 'DATA_INTEGRITY_ERROR',
  INVALID_DATA_FORMAT = 'INVALID_DATA_FORMAT',

  // Authentication/Authorization
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // RabbitMQ specific
  QUEUE_NOT_FOUND = 'QUEUE_NOT_FOUND',
  MESSAGE_PROCESSING_ERROR = 'MESSAGE_PROCESSING_ERROR',
  QUEUE_CONNECTION_ERROR = 'QUEUE_CONNECTION_ERROR',

  // SAP specific
  SAP_CONNECTION_ERROR = 'SAP_CONNECTION_ERROR',
  SAP_DATA_SYNC_ERROR = 'SAP_DATA_SYNC_ERROR',
  SAP_AUTHENTICATION_ERROR = 'SAP_AUTHENTICATION_ERROR',

  // Label/Print specific
  LABEL_TEMPLATE_NOT_FOUND = 'LABEL_TEMPLATE_NOT_FOUND',
  PRINT_JOB_FAILED = 'PRINT_JOB_FAILED',
  PRINTER_NOT_AVAILABLE = 'PRINTER_NOT_AVAILABLE',
  INVALID_LABEL_FORMAT = 'INVALID_LABEL_FORMAT',
}

// NUNCA retorna 500 - sempre converte para outros códigos
export const HttpStatusByErrorCode: Record<ErrorCode, number> = {
  // 400 Bad Request
  [ErrorCode.BAD_REQUEST]: 400,
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.INVALID_DATA_FORMAT]: 400,

  // 401 Unauthorized
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,
  [ErrorCode.INVALID_TOKEN]: 401,
  [ErrorCode.SAP_AUTHENTICATION_ERROR]: 401,

  // 403 Forbidden
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.INSUFFICIENT_PERMISSIONS]: 403,
  [ErrorCode.OPERATION_NOT_ALLOWED]: 403,

  // 404 Not Found
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.DATA_NOT_FOUND]: 404,
  [ErrorCode.QUEUE_NOT_FOUND]: 404,
  [ErrorCode.LABEL_TEMPLATE_NOT_FOUND]: 404,

  // 405 Method Not Allowed
  [ErrorCode.METHOD_NOT_ALLOWED]: 405,

  // 409 Conflict
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.DUPLICATE_ENTRY]: 409,

  // 422 Unprocessable Entity
  [ErrorCode.UNPROCESSABLE_ENTITY]: 422,
  [ErrorCode.BUSINESS_RULE_VIOLATION]: 422,
  [ErrorCode.DATA_INTEGRITY_ERROR]: 422,
  [ErrorCode.INSUFFICIENT_RESOURCES]: 422,
  [ErrorCode.MESSAGE_PROCESSING_ERROR]: 422,
  [ErrorCode.SAP_DATA_SYNC_ERROR]: 422,
  [ErrorCode.PRINT_JOB_FAILED]: 422,
  [ErrorCode.INVALID_LABEL_FORMAT]: 422,

  // 429 Too Many Requests
  [ErrorCode.TOO_MANY_REQUESTS]: 429,

  // 502 Bad Gateway (ao invés de 500)
  [ErrorCode.EXTERNAL_SERVICE_ERROR]: 502,
  [ErrorCode.INTEGRATION_ERROR]: 502,
  [ErrorCode.SAP_CONNECTION_ERROR]: 502,
  [ErrorCode.QUEUE_CONNECTION_ERROR]: 502,

  // 503 Service Unavailable
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.PRINTER_NOT_AVAILABLE]: 503,

  // 504 Gateway Timeout
  [ErrorCode.GATEWAY_TIMEOUT]: 504,
  [ErrorCode.TIMEOUT_ERROR]: 504,
};
